#
# Power save related files
#
obj-y := pm.o runtime.o

obj-$(CONFIG_DBX500_PRCMU_QOS_POWER)	+= prcmu-qos-power.o
obj-$(CONFIG_DBX500_CONTEXT) 		+= context.o context_arm.o context-db8500.o context-db5500.o context-db9540.o
obj-$(CONFIG_DBX500_CPUIDLE) 		+= timer.o
obj-$(CONFIG_UX500_SUSPEND)		+= suspend.o
obj-$(CONFIG_UX500_SUSPEND_DBG)		+= suspend_dbg.o
obj-$(CONFIG_UX500_PM_PERFORMANCE)	+= performance.o
obj-$(CONFIG_UX500_USECASE_GOVERNOR)	+= usecase_gov.o
