#
# Makefile for the linux kernel, SEC Debug.
#

obj-$(CONFIG_SAMSUNG_PANIC_DISPLAY_LSOF)	+= sec_lsof.o
obj-$(CONFIG_SAMSUNG_PANIC_DISPLAY_DEVICES)	+= sec_pmic.o
obj-$(CONFIG_SAMSUNG_PANIC_DISPLAY_DEVICES)	+= sec_i2c.o
obj-$(CONFIG_SAMSUNG_PANIC_LCD_DISPLAY)		+= khb_main.o khb_lcd.o

