#
# Makefile for the CG2900 FM Radio Driver
#

radio_cg2900-objs := radio-cg2900.o cg2900_fm_api.o cg2900_fm_driver.o

obj-$(CONFIG_RADIO_CG2900) += radio_cg2900.o

ccflags-y :=                                    \
        -Idrivers/staging/cg2900/include \


