##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		:


obj-$(CONFIG_PROXIMITY_CM3607)	+= cm3607.o
obj-$(CONFIG_PROXIMITY_GP2A)	+= gp2a.o
obj-$(CONFIG_LIGHT_PROX_GP2A)	+= gp2a_light_prox.o
obj-$(CONFIG_PROXIMITY_TMD2672)	+= tmd2672.o
obj-$(CONFIG_PROXIMITY_PX3215)  += px3215.o
obj-$(CONFIG_PROXIMITY_PX3315)  += px3315.o



