#
# Copyright (C) ST-Ericsson SA 2010
# Author: Martin Hovang (martin.xm.hovang@stericsson.com)
# License terms: GNU General Public License (GPL) version 2
#

obj-$(CONFIG_TEE_SUPPORT) += tee_service.o
obj-$(CONFIG_TEE_SUPPORT) += tee_driver.o
