obj-$(CONFIG_MODEM)       := modem_access.o
obj-$(CONFIG_MODEM_U8500) += modem_u8500.o
obj-$(CONFIG_U8500_SHRM)  += shrm/
obj-$(CONFIG_MODEM_M6718) += modem_m6718.o
obj-$(CONFIG_MODEM_M6718_SPI) += m6718_spi/
obj-$(CONFIG_MODEM_U5500_MCDD)  += mcdd.o
obj-$(CONFIG_U8500_KERNEL_CLIENT)	+= u8500_client.o
