#
# Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_PHONE_MODEMCTL)	+= modemctl/
obj-$(CONFIG_PHONE_ONEDRAM)		+= onedram/
obj-$(CONFIG_PHONE_SVNET)		+= svnet/
